languages:
  vim:
    lint-command: vint -
    lint-stdin: true

  markdown:
    lint-command: markdownlint -s
    lint-stdin: true
    lint-formats:
      - '%f: %l: %m'
  go:
    lint-command: golangci-lint run
    lint-stdin: false

  sh:
    lint-command: shellcheck -f gcc -
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
