#!/bin/zsh

# inuxのヘッダファイル群。makeするときに何やかや出番が多い
sudo pacman -S --noconfirm \
  linux-headers

# 開発でよく使うツール、言語系
sudo pacman -S --noconfirm \
  inotify-tools \
  jq httpie asciinema \
  dialog \
  openssh \
  git github-cli tig \
  sqlite postgresql mysql \
  deno yarn go python python-pip python-language-server python-poetry luarocks nodejs npm \
  autoconf automake bison fakeroot flex gcc gettext make ninja \
  man-db \
  man-pages \
  shellcheck \
  teensy-loader-cli \
  tidy \
  docker aws-cli docker-compose

if [ command -v yay >/dev/null ]; then
  : # noop
else
  rm -rf ./yay
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si
  cd -
  rm -rf ./yay
fi

# シェルを便利にしたい群
yay -S --noconfirm \
  zsh zsh-syntax-highlighting zsh-completions \
  diff-so-fancy \
  direnv-bin

# CLI人権ツール群
yay -S --noconfirm \
  wget \
  ripgrep \
  neovim-nightly-bin

# Libraries
yay -S --noconfirm \
  libnotify \
  libgnome-keyring \
  libtool \
  lib32-glibc

# Bash CLIツール群
yay -S --noconfirm \
  bash \
  binutils \
  coreutils \
  diffutils \
  findutils \
  patch \
  sed \
  which

# その他
yay -S --noconfirm \
  asciinema \
  bluez-utils \
  chrome-gnome-shell \
  darktable \
  discord \
  fwupd \
  gimp \
  gimp-nufraw \
  google-chrome \
  gstreamer gst-plugins-ugly \
  gyazo \
  nordic-theme \
  ibus-mozc \
  inkscape \
  peek \
  screenkey \
  seahorse \
  slack-desktop \
  testdisk \
  ulauncher \
  ufraw-thumbnailer
