#!/bin/zsh

# inuxのヘッダファイル群。makeするときに何やかや出番が多い
sudo pacman -S --noconfirm \
  linux-headers

# 開発でよく使うツール、言語系
sudo pacman -S --noconfirm \
  inotify-tools \
  jq httpie asciinema \
  dialog \
  openssh \
  git github-cli tig \
  sqlite postgresql mysql \
  deno yarn go python python-pip python-language-server python-poetry luarocks nodejs npm \
  autoconf automake bison fakeroot flex gcc gettext make ninja pkg-config \
  man-db \
  man-pages \
  shellcheck \
  teensy-loader-cli \
  tidy \
  base-devel \
  docker aws-cli docker-compose

if [ command -v paru >/dev/null ]; then
  : # noop
else
  rm -rf ./paru
  git clone https://aur.archlinux.org/paru.git
  cd paru
  makepkg -si
  cd -
  rm -rf ./paru
fi

# シェルを便利にしたい群
paru -S --noconfirm \
  zsh zsh-syntax-highlighting zsh-completions \
  diff-so-fancy \
  direnv-bin

# CLI人権ツール群
paru -S --noconfirm \
  wget \
  ripgrep \
  luajit-2.1

# Neovim
nvim_tmpdir="$(mktemp -d)"
trap "rm -rfv $nvim_tmpdir" EXIT
git clone --depth 1 -b nightly https://github.com/neovim/neovim "$nvim_tmpdir/neovim"
pushd "$nvim_tmpdir/neovim"
make -j4
sudo make install
sudo cp ./runtime/nvim.desktop /usr/share/applications
popd

# Libraries
paru -S --noconfirm \
  libnotify \
  libgnome-keyring \
  libtool \
  lib32-glibc

# Bash CLIツール群
paru -S --noconfirm \
  bash \
  binutils \
  coreutils \
  diffutils \
  findutils \
  patch \
  sed \
  which

# その他
paru -S --noconfirm \
  asciinema \
  bluez-utils \
  chrome-gnome-shell \
  darktable \
  discord \
  fwupd \
  gimp \
  gimp-nufraw \
  google-chrome \
  gstreamer gst-plugins-ugly \
  gyazo \
  nordic-theme \
  ibus-mozc \
  inkscape \
  peek \
  screenkey \
  seahorse \
  slack-desktop \
  testdisk \
  gnome-tweaks \
  ulauncher wmctrl \
  ufraw-thumbnailer
