#!env zsh

set -ex

## DotFiles:
DOTFILES=${HOME}/.config
DOTPROJECT=${HOME}/Projects/github.com/kyoh86/dotfiles
DOTTMP=${HOME}/dotfiles-main

# get dot files
if [[ -f ${DOTFILES}/setup ]]; then
  :
else
  rm -rf ${DOTTMP}
  curl -L https://github.com/kyoh86/dotfiles/archive/main.tar.gz | tar xvz

  mkdir -p ${DOTFILES}
  cp -RPf ${DOTTMP}/* ${DOTFILES}
  rm -rf ${DOTTMP}
fi
source ${DOTFILES}/zsh/.zshenv

# OS別のセットアップ
[ -f ${DOTFILES}/setup_`uname` ] && source ${DOTFILES}/setup_`uname`

yarn global add \
          typescript-language-server \
          vim-language-server

GOBIN="${HOME}/.local/bin/" go get github.com/kyoh86/gordon
gordon restore "${DOTFILES}/gordon/bundle"

# replace dotfiles
if [[ -d ${DOTFILES}/.git ]]; then
  git -C ${DOTFILES} pull
else
  rm -rf "${DOTPROJECT}"
  git clone https://github.com/kyoh86/dotfiles "${DOTPROJECT}"
  cp -r "${DOTFILES}"/* "${DOTPROJECT}"
  rm -rf ${DOTFILES}
  ln -sf "${DOTPROJECT}" "${DOTFILES}"
fi

echo "DONE🍺"
