#!/bin/zsh

gsettings set org.gnome.desktop.peripherals.keyboard repeat true
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 80
gsettings set org.gnome.desktop.peripherals.keyboard delay 200
