#!/bin/zsh

set -e

## DotFiles:
DOTFILES=${HOME}/.config

# get dot files
if [[ -f ${DOTFILES}/setup ]]; then
  :
else
  DOTTMP=${HOME}/dotfiles-master
  rm -rf ${DOTTMP}
  curl -L https://github.com/kyoh86/dotfiles/archive/master.tar.gz | tar xv -

  mkdir -p ${DOTFILES}
  cp -RPf ${DOTTMP}/* ${DOTFILES}
  rm -rf ${DOTTMP}
fi
source ${DOTFILES}/zsh/.zshenv

# OS別のセットアップ
[ -f ${DOTFILES}/setup_`uname` ] && . ${DOTFILES}/setup_`uname`

# OS別のgitconfig
function link_os() {
  local prefix="$1"
  if [ -z "${prefix}" ]; then
    return
  fi
  local dest="${prefix}_$(uname)"
  local link="${prefix}_os"
  if [ -f "${dest}" ]; then
    ln -s "${dest}" "${link}"
  else
    touch "${link}"
  fi
}
link_os "${DOTFILES}/git/config"

yarn global add \
          typescript-language-server \
          vim-language-server

# replace dotfiles
if [[ -d ${DOTFILES}/.git ]]; then
  git -C ${DOTFILES} pull
else
  rm -rf ${DOTFILES}
  git clone git@github.com:kyoh86/dotfiles ${DOTFILES}
fi

echo "DONE🍺"
