# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    patch: '!echo ''{"ref":"''$(git symbolic-ref refs/remotes/origin/HEAD | awk -F''/'' ''{print $NF}'')''","inputs":{"method":"patch"}}'' | gh api -X POST repos/:owner/:repo/actions/workflows/release.yaml/dispatches --input -'
    pr-draft: pr create --assignee "@me" --draft
    branch: '!git remote set-head origin --auto && git fetch && git branch --no-track "$1" "$(git symbolic-ref refs/remotes/origin/HEAD)" && git switch "$1" && git commit --allow-empty -m "wip: $1" && gh pr create --assignee "@me" --draft'
